app: infoio.o contact.o main.o
	gcc infoio.o contact.o main.o -o app

infoio.o: infoio.c
	gcc -c infoio.c

contact.o: contact.c
	gcc -c contact.c

main.o: main.c
	gcc -c main.c

clean:
	rm infoio.o contact.o main.o -rf



